<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.1.1.343
*/

require_once('recaptchalib.php');
require_once('form_process.php');

$form = array(
	'subject' => 'Sign Up Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'recaptcha' => array(
		'private_key' => '1234'
	),
	'fields' => array(
		'custom_U5049' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Last Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Last Name\' is required.'
			)
		),
		'custom_U5061' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'MI',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'MI\' is required.'
			)
		),
		'custom_U5097' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'First Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'First Name\' is required.'
			)
		),
		'custom_U5112' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Course',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Course\' is required.'
			)
		),
		'custom_U5198' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Year',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Year\' is required.'
			)
		),
		'custom_U5447' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Cell Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Cell Phone\' is required.'
			)
		),
		'custom_U5459' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Student Number',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Student Number\' is required.'
			)
		),
		'recaptcha_response_field' => array(
			'order' => 8,
			'type' => 'recaptcha',
			'label' => 'Image Verification',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Image Verification\' is required.',
				'format' => 'Incorrect reCAPTCHA value.'
			)
		)
	)
);

process_form($form);
?>
